#!/bin/bash
# help.sh - Help guide for AI training

echo "🆘 TextMeWhen AI Training Help"
echo "=============================="
echo ""
echo "📋 Common Commands:"
echo "  ./start_training.sh     - Start the training interface"
echo "  ./stop_training.sh      - Stop the training server"
echo "  ./upload_changes.sh     - Share your improvements"
echo "  ./download_updates.sh   - Get latest improvements"
echo "  ./check_status.sh       - Check system status"
echo ""
echo "🌐 Training Interface:"
echo "  http://localhost:8000/user_friendly_trainer.html"
echo ""
echo "🎯 What You're Doing:"
echo "  - Teaching AI to recognize patterns"
echo "  - Fixing misclassified reminders"
echo "  - Improving accuracy for future requests"
echo ""
echo "🔧 Common Issues:"
echo ""
echo "❌ 'PHP not found'"
echo "   Fix: brew install php"
echo ""
echo "❌ 'Permission denied'"
echo "   Fix: chmod +x *.sh"
echo ""
echo "❌ 'Browser doesn't open'"
echo "   Fix: Go to http://localhost:8000/user_friendly_trainer.html"
echo ""
echo "❌ 'No data shows up'"
echo "   Fix: Make sure reminders exist in the database"
echo "   Try: php quick_generate_parser.php"
echo ""
echo "📞 Need More Help?"
echo "   - Check the README.md file"
echo "   - Run ./check_status.sh to see what's wrong"
echo "   - Ask the person who sent you this!"
echo ""
echo "🎉 Remember: Every fix you make helps the AI get smarter!"
echo ""